name: Feature request
description: Suggest an idea for this project
title: "[New Feature]: "
labels: ["Feature-Request"]
body:
  - type: markdown
    attributes:
      value: |
        > _Feature requests are not typically handled in the repository, you may suggest features in the Discord.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      description: A clear and concise description of your request.
      placeholder: Tell us what you want
      value: "I'd like it if [...]"
    validations:
      required: true
